### PR TITLE
qutip-v4.1.0 build 1

### PR DESCRIPTION
**Pull request by ajgpitch**
win py27 builds added back in

### CODE REVIEW

**Comment by ajgpitch** [comment]
@isuruf This is the recipe we actually want. I had a response from AppVeyor when they showed the cpu_count() working in Python 2.7.13 on their env, so perhaps the issue is sporadic. Let's see what happens.

**Comment by ajgpitch** [comment]
@isuruf On the subject of sporadic issues: I had to run the rerender 4 times before all the appveyor builds were included. The first 2 did not have any py36, the third had py36 for x64, the fourth added py36 x86 nack in.

**Comment by ajgpitch** [comment]
We see the problem persists. I am discussing at
http://help.appveyor.com/discussions/problems/6280-conda-forge-build-test-failing-on-multiprocessingnum_cpus-with-python-27

**Comment by isuruf** [comment]
I think conda-build=2.1.6 was the issue. conda-build was updated to 2.1.6 recently (That's why in the previous PR, it worked at the beginning and didn't at the end).
We've downgraded to conda-build=2.1.4 at conda-forge due to various reasons.

I've restarted the build and it works fine now

**Comment by ajgpitch** [comment]
Thanks for solving the mystery @isuruf. I'll merge this now. And update the AppVeyor people

**Pull request merged**
