### PR TITLE
update v4 to v4.7.6

### PR DESCRIPTION
**Pull request by ajgpitch**
Checklist
* [ Y] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [Y ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [Y ] Ensured the license file is being packaged.

Increase countstat stability.
Exclude scipy 1.13 from in the requirements

### CODE REVIEW

**Comment by ajgpitch** [comment]
I'm off to the hills shortly. Please someone merge this if looks okay.

**Review by hodgestar — APPROVED** [review]
The change looks good to me, but I see the build is failing.

**Comment by hodgestar** [comment]
@conda-forge-admin, please restart ci

**Comment by hodgestar** [comment]
It looks like the build failure was a networking issue. Have asked the bot to re-run the builds.

**Review by Ericgig — APPROVED** [review]

**Comment by ajgpitch** [comment]
Thanks @hodgestar and @Ericgig. Just updated my qutip via conda and all good.

**Pull request merged**
