### PR TITLE
Add Cython to run requirements

### LINKED ISSUE #53: Cython dependency
This conda recipe does not set Cython as a run dependency, but `install_requires` in qutip's `setup.py` does include Cython.

I know there is some history of discussion regarding this in #8 (and also that handling Cython in qutip has caused some problems like https://github.com/qutip/qutip/issues/1246 as well). It seems like the initial feedstock PR included Cython as a run dependency but the conda-forge reviewers discouraged that because it seemed unlikely Cython was really needed at run time. At the time, qutip had autocompile code that imported Cython and that was patched out in the recipe here. Now it seems that all Cython imports are wrapped in `try`'s so it is okay to run qutip without Cython (but I have not studied how qutip uses Cython at run time in detail, so I am not positive; that is why I am opening an issue here rather than proposing removing Cython from qutip's install_requires).

My suggestion is that this feedstock should be consistent with the upstream qutip. So either both should specify Cython as a dependency or neither. Until a time when upstream qutip removes Cython as an install_requires dependency, I propose that this feedstock should specify it as a run dependency.

The mismatch in requirements does not produce too bad of outcomes, but there is some consequence. Personally, I try to keep my conda environments as purely composed of conda packages as possible but sometimes it is necessary to install packages with `pip`. I have found that recent versions of `pip` will install missing dependencies when you run other installs. So when I have the qutip conda package installed, I end up getting Cython installed by `pip` the next time I use `pip` because `pip` sees it as a missing dependency of qutip.

### PR DESCRIPTION
**Pull request by wshanks**
This matches the install_requires specified in qutip's setup.py.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes #53 by adding Cython to the run dependencies to mirror the `install_requires` in qutip's setup.py.

### CODE REVIEW

**Comment by willsALMANJ** [comment]
@conda-forge-admin, please rerender

**Comment by jakelishman** [comment]
At the time this was opened, it was correct in principle - `Cython` was listed as a run-time dependency of QuTiP.  However, the real "bug" was more in that dependency list; Cython was more like an optional dependency, because you could use almost all the features of QuTiP without it.  Now on `master` (and for the next release), `Cython` is correctly listed as only needed for run-time compilation, so it's no longer correct for it to be in the recipe.

Thanks for suggesting this, and sorry for the lack of response before now.  I'm closing it now since upstream changes have obsoleted the PR, but still thanks.

**Comment by wshanks** [comment]
Yes, this was a quick fix for #53 with the main goal being that `conda install qutip` not cause `pip check` to fail. It is good to hear that with the next release of qutip #53 can be closed.

**Comment by jakelishman** [comment]
Ah, thanks for reminding me about the issue.  I'll close it once we've done the 4.6 release (hopefully within a fortnight or so).

**Pull request closed without merging**
