### PR TITLE
Release 5.0.3 with numpy 2

### PR DESCRIPTION
**Pull request by Ericgig**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Update version number from #100 to build from qutip 5.0.3.
Updated cython version.
Updated maintainers.
Numpy 2 is not available on pypy with python 3.9 for windows and mac, I skipped these wheels. But qutip would build using numpy 1.22 without issues, it's only after the compilation that a sanity check failed due to the requirements...

### CODE REVIEW

**Comment by Ericgig** [comment]
@conda-forge-admin, please rerender

**Comment by Ericgig** [comment]
@conda-forge-admin, please rerender

**Comment by Ericgig** [comment]
@conda-forge-admin, please rerender

**Review by ajgpitch — APPROVED** [review]
All looks good

**Pull request merged**
