### PR TITLE
Release 4.6.2

### PR DESCRIPTION
**Pull request by quantshah**
Updated recipe for v4.6.2

### CODE REVIEW

**Comment by jakelishman** [comment]
@conda-forge-admin, please rerender

**Comment by jakelishman** [comment]
Interesting - it's been about a month since we released 4.6.1, so I'm surprised that none of our dependencies got any updates in conda-forge-pinning since then!

**Review by jakelishman — APPROVED** [review]

**Review by hodgestar — APPROVED** [review]
Woot!

**Comment by jakelishman** [comment]
Let's leave this for Shahnawaz to merge, so he's done the entire release!  Shahnawaz, you culd also post about it in the discord/mailing list if you liked as well - it'd be particularly nice to publically show off the work of the Unitary Hack contributors.

**Comment by quantshah** [comment]
Thanks for all the help @hodgestar and @jakelishman. This had been a very smooth experience. I will post the new updates on the discord/mailing list tomorrow.

**Pull request merged**
